# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6
    networks:
      - app-network

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydb"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: "your_jwt_secret"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
